name: 💡 Feature request
description: Suggest an idea for this project
title: "Your title here"
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to make this suggestion!
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please [search](https://github.com/openresearchcalendar/openresearchcalendar.github.io/issues?q=is%3Aissue) to see if an issue already exists for the feature you are suggesting.
      options:
      - label: I have searched the existing open and closed issues
        required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: feature-problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: What's the problem?
      value: "Ex. I'm always frustrated when [...]"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: What's the solution?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: What's the alternative?
    validations:
      required: false
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the feature you are suggesting!

        Tip: You can attach images/screenshots or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/openresearchcalendar/openresearchcalendar.github.io/blob/master/Code_of_Conduct.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
